language: node_js
node_js:
  - '6'

cache:
  directories:
  - node_modules

install:
  - npm install

services:
  - postgresql

env:
  global:
    - NODE_ENV=test
    - PGPORT=5432
    - CC_TEST_REPORTER_ID=e8a35ce07efee405b89c962e132e8b5cffc2938785406ed448ad0abefd492405

before_script:
  - psql -c 'create database documentor_test;' -U postgres
  - psql -c "CREATE USER linnettewanjiru WITH PASSWORD '';" -U postgres
  - sequelize db:migrate
  - sequelize db:seed:all
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
