language: node_js
node_js:
  - '6'
script:
  - npm run server-test-path
code_climate:
  repo_token: e8a35ce07efee405b89c962e132e8b5cffc2938785406ed448ad0abefd492405
services:
  - postgresql
before_script:
  - cp ./database.yml.travis ./server/config/config.json
env:
  global:
    - PGPORT=5432
addons:
  postgresql: "9.6"