language: node_js
node_js:
  "stable"
install: npm install
services:
  - postgresql
env: 
  - NODE_ENV=test

  global:
    - PGPORT=5432
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER linnettewanjiru WITH PASSWORD '';" -U postgres
  - npm run build
  - sequelize db:migrate
  - sequelize db:seed:all

script: npm test

after_success: npm run coverage

