language: node_js
node_js:
  - "6"
  - "8"
  - "7"
script:
  - npm test
addons:
  postgresql: "9.6"
  code_climate:
    repo_token: e8a35ce07efee405b89c962e132e8b5cffc2938785406ed448ad0abefd492405
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
services:
  - postgresql
