language: node_js
node_js:
  - "6"
  - "8"
  - "7"
script:
  - npm test
addons:
  code_climate:
    repo_token: e8a35ce07efee405b89c962e132e8b5cffc2938785406ed448ad0abefd492405
before_install:
  - npm install -g dredd@4.1.3
before_script:
  - dredd
